services:
  - type: web
    name: crypto-news-tg-bot
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false
      - key: POST_LANGUAGE
        value: uk
